name: coverage

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3.3.0
    - uses: ruby/setup-ruby@f321cf5a4d1533575411f8752cf25b86478b0442 # v1.193.0
      with:
        ruby-version: '3.0'
    - name: Install dependencies
      run: gem install test-unit coveralls
    - name: Run test
      env:
        COVERALLS: "yes"
      run: ruby -Ilib exe/rake
